Apply patches from github not relative paths
Icinga/ipl-scheduler pull request #18
Opened 2022-11-25 10:59 UTC by yhabteab

2022-11-25 12:45 UTC, nilmerg commented
Is this really the only solution? Is this is a known limitation of the plugin?

2022-11-25 12:59 UTC, yhabteab commented
> Is this really the only solution? Is this is a known limitation of the plugin?

https://github.com/cweagans/composer-patches/issues/315

2022-12-12 14:49 UTC, lippserd requested changes
Please add a commit description. You may also include the upstream issue link.

2022-12-13 14:48 UTC, yhabteab commented
> **NOTE**
> We need to use a release tag for the url and not the main branch

2023-01-09 09:48 UTC, closed without merging