RRule: Register end time using `Rule::setUntil()` instead
Icinga/ipl-scheduler pull request #36
Opened 2023-03-29 07:38 UTC by nilmerg

fixes #35

2023-03-29 12:47 UTC, yhabteab requested changes

2023-03-29 12:47 UTC, yhabteab commented on tests/RRuleTest.php
> +            ->endAt(new DateTime('2024-01-01T12:00:00', new \DateTimeZone('UTC')));
Can you please import this.

2023-03-29 12:51 UTC, nilmerg commented on tests/RRuleTest.php
> +            $rrule->jsonSerialize()
The intention for this test, is to verify that `UNTIL` is used, not `DTEND`. Hence this must be done this way.

2023-03-29 13:00 UTC, yhabteab commented on tests/RRuleTest.php
> +            $rrule->jsonSerialize()
But if you don't set the `DTEND` with `setEndDate()`, which is not the case here, it won't be used in any way.

2023-03-29 13:15 UTC, nilmerg commented on tests/RRuleTest.php
> +            $rrule->jsonSerialize()
Please lookup what a regression test is. Then you probably understand what I want to achieve.

2023-04-03 07:00 UTC, yhabteab approved these changes

2023-04-03 07:01 UTC, merged