RRule: Include set timezone in serialized result
Icinga/ipl-scheduler pull request #38
Opened 2023-03-29 08:08 UTC by nilmerg

fixes #37
blocked by #39

2023-03-29 13:21 UTC, nilmerg commented
Partly obsolete since #40, but for `UNTIL` still relevant.

2023-04-03 07:22 UTC, yhabteab requested changes

2023-04-03 07:22 UTC, yhabteab commented on tests/RRuleTest.php
[As far as I understand](http://php.adamharvey.name/manual/en/function.date-default-timezone-set.php), `date_default_timezone_set();` only sets the timezone for the current script, so I don't think that you need the `try...finally` to reset the timezone.

2023-04-03 07:22 UTC, yhabteab commented on tests/RRuleTest.php
> +                ->jsonSerialize()));
```suggestion
            $rrule = RRule::fromJson(
                json_encode(
                    RRule::fromFrequency(RRule::DAILY)
                        ->startAt($startWithTz)
                        ->endAt($endWithTz)
                        ->jsonSerialize()
                )
            );
```

2023-04-03 08:02 UTC, nilmerg commented on tests/RRuleTest.php
*the current script* is the entire test run. i.e. all tests combined.

2023-04-03 08:17 UTC, yhabteab approved these changes

2023-04-03 10:22 UTC, merged